services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy-lb
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - app1
      - app2
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "20MB"
  app1:
    build: .
    container_name: app1
    networks:
      - app-network
      - payment-processor
    depends_on:
      - redis
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_URI=redis://redis:6379
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"
  app2:
    build: .
    container_name: app2
    networks:
      - app-network
      - payment-processor
    depends_on:
      - redis
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_URI=redis://redis:6379
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "130MB"
    networks:
      - app-network
networks:
  payment-processor:
    external: true
  app-network:



